version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1-node
    steps:
      - checkout
      - run:
          name: Run npm build
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/python:3.10.1-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages
            mkdir -p ~/.ssh      
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config user.email "jonbot@jonbannister.com"
            git config user.name "jonbot"
      - add_ssh_keys:
          fingerprints:
            - "e6:56:b5:74:9e:89:d9:7d:c2:58:68:21:e9:73:38:43"
      - run:
          name: Add metadata to output
          command: |
            touch ./dist/.nojekyll
            echo "jonbannister.com" > ./dist/CNAME
      - run:
          name: Deploy dist to gh-pages branch
          command: | 
            function npm-do { (PATH=$(npm bin):$PATH; eval $@;) }
            npm-do gh-pages --dotfiles --message "Autodeployed" --dist dist/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master