version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1-node
    steps:
      - checkout
      - run:
          name: Run npm build
          command: |
            npm install
            npm run build
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "jonbot@jonbannister.com"
            git config user.name "jonbot"
      - add_ssh_keys:
          fingerprints:
            - "e6:56:b5:74:9e:89:d9:7d:c2:58:68:21:e9:73:38:43"
      - run:
          name: Deploy dist to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist dist/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build